const HardwareProducts = [
    // Paints & Finishes
    {
        id: "HW-PNT-001",
        category: "Paints & Finishes",
        name: "Crown Walplast Skim Coat",
        description: "Premium interior/exterior skim coat for smooth wall finishes before painting. Easy to mix and apply.",
        price: "KSh 1,200",
        rating: 4.8,
        stock: 45,
        image: "assets/images/products/hardware/photo_2026-03-09_06-38-03.jpg",
        images: ["assets/images/products/hardware/photo_2026-03-09_06-38-03.jpg", "assets/images/products/hardware/photo_1_2026-03-09_04-54-32.jpg"],
        brand: "Crown Paints",
        specs: { "Weight": "25kg", "Application": "Interior & Exterior", "Color": "White", "Coverage": "1.5 kg/sqm/mm" }
    },
    {
        id: "HW-PNT-002",
        category: "Paints & Finishes",
        name: "DuraCoat Skim Coat",
        description: "High adhesion skim coat putty for concrete and masonry surfaces. Fills cracks and pinholes effectively.",
        price: "KSh 1,150",
        rating: 4.7,
        stock: 32,
        image: "assets/images/products/hardware/photo_2_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_2_2026-03-09_04-54-32.jpg"],
        brand: "DuraCoat",
        specs: { "Weight": "25kg", "Application": "Interior/Exterior", "Drying Time": "24 Hours" }
    },
    {
        id: "HW-PNT-003",
        category: "Paints & Finishes",
        name: "DuraCoat Silicone Exterior Emulsion",
        description: "100% waterproof exterior silicone emulsion paint. Brilliant white finish with high UV and fungal resistance.",
        price: "KSh 8,500",
        rating: 4.9,
        stock: 18,
        image: "assets/images/products/hardware/photo_3_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_3_2026-03-09_04-54-32.jpg"],
        brand: "DuraCoat",
        specs: { "Volume": "4 Litres", "Color": "Brilliant White", "Feature": "100% Waterproof", "Durability": "7 Years+" }
    },
    {
        id: "HW-PNT-004",
        category: "Paints & Finishes",
        name: "Duraplast Weathercoat",
        description: "Premium exterior emulsion paint offering maximum weather resistance. Protects against rain, sun, and dirt.",
        price: "KSh 4,200",
        rating: 4.6,
        stock: 24,
        image: "assets/images/products/hardware/photo_10_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_10_2026-03-09_04-54-32.jpg"],
        brand: "DuraCoat",
        specs: { "Volume": "4 Litres", "Finish": "Matt", "Application": "Exterior", "Coverage": "12-14 sqm/L" }
    },
    {
        id: "HW-PNT-005",
        category: "Paints & Finishes",
        name: "DuraCoat Superfast",
        description: "Quick-drying premium paint for fast residential and commercial renovations. Excellent hiding power.",
        price: "KSh 3,800",
        rating: 4.5,
        stock: 40,
        image: "assets/images/products/hardware/photo_4_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_4_2026-03-09_04-54-32.jpg"],
        brand: "DuraCoat",
        specs: { "Volume": "4 Litres", "Drying Time": "Fast-Dry", "Type": "Emulsion" }
    },
    {
        id: "HW-PNT-006",
        category: "Paints & Finishes",
        name: "Crown Permaplast Exterior Emulsion",
        description: "High-build textured finish that protects walls against harsh weather. No harmful smells.",
        price: "KSh 9,500",
        rating: 4.8,
        stock: 15,
        image: "assets/images/products/hardware/photo_11_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_11_2026-03-09_04-54-32.jpg"],
        brand: "Crown Paints",
        specs: { "Volume": "20 Litres", "Finish": "Textured", "Application": "Exterior" }
    },
    {
        id: "HW-PNT-007",
        category: "Paints & Finishes",
        name: "Crown Covermatt Emulsion",
        description: "Standard quality interior emulsion paint with a smooth matt finish. Economical choice for large areas.",
        price: "KSh 3,200",
        rating: 4.4,
        stock: 50,
        image: "assets/images/products/hardware/photo_12_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_12_2026-03-09_04-54-32.jpg"],
        brand: "Crown Paints",
        specs: { "Volume": "20 Litres", "Finish": "Matt", "Application": "Interior" }
    },
    {
        id: "HW-PNT-008",
        category: "Paints & Finishes",
        name: "Crown Ruff N Tuff",
        description: "Premium grade textured wall finish. No harmful smells. Tough and durable for exterior protection.",
        price: "KSh 5,800",
        rating: 4.9,
        stock: 22,
        image: "assets/images/products/hardware/photo_5_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_5_2026-03-09_04-54-32.jpg"],
        brand: "Crown Paints",
        specs: { "Weight": "30kg", "Finish": "Textured", "Grade": "Premium" }
    },
    {
        id: "HW-PNT-009",
        category: "Paints & Finishes",
        name: "DuraCoat Real Rock Finish",
        description: "Natural stone finish paint for exterior walls. Provides a luxurious, durable real rock texture.",
        price: "KSh 7,500",
        rating: 4.7,
        stock: 10,
        image: "assets/images/products/hardware/photo_4_2026-03-09_04-54-49.jpg",
        images: ["assets/images/products/hardware/photo_4_2026-03-09_04-54-49.jpg"],
        brand: "DuraCoat",
        specs: { "Weight": "30kg", "Finish": "Stone/Rock Texture", "Application": "Exterior" }
    },
    {
        id: "HW-PNT-010",
        category: "Paints & Finishes",
        name: "DuraCoat Vinyl Silk",
        description: "Premium silk emulsion paint. Highly washable, stain-resistant, and leaves a beautiful soft sheen.",
        price: "KSh 4,800",
        rating: 4.8,
        stock: 35,
        image: "assets/images/products/hardware/photo_13_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_13_2026-03-09_04-54-32.jpg"],
        brand: "DuraCoat",
        specs: { "Volume": "4 Litres", "Finish": "Silk/Sheen", "Washability": "High" }
    },
    {
        id: "HW-PNT-011",
        category: "Paints & Finishes",
        name: "DuraCoat Super Gloss",
        description: "High-quality enamel trim paint for wood and metal surfaces. Brilliant high-gloss finish.",
        price: "KSh 3,500",
        rating: 4.6,
        stock: 42,
        image: "assets/images/products/hardware/photo_14_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_14_2026-03-09_04-54-32.jpg"],
        brand: "DuraCoat",
        specs: { "Volume": "4 Litres", "Finish": "High Gloss", "Application": "Wood & Metal" }
    },
    {
        id: "HW-PNT-012",
        category: "Paints & Finishes",
        name: "DuraCoat Ultima Play Stucco",
        description: "Decorative luxury textured finish (e.g., 2716P or Glitz). Creates elegant patterns on interior feature walls.",
        price: "KSh 12,000",
        rating: 5.0,
        stock: 12,
        image: "assets/images/products/hardware/photo_6_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_6_2026-03-09_04-54-32.jpg", "assets/images/products/hardware/photo_7_2026-03-09_04-54-32.jpg"],
        brand: "DuraCoat",
        specs: { "Finish": "Special Effect/Stucco", "Application": "Interior Feature Walls", "Coverage": "Varies by pattern" }
    },
    // Building Materials
    {
        id: "HW-BLD-001",
        category: "Building Materials",
        name: "Bamburi Portland Cement",
        description: "High-strength general purpose cement for all construction needs. Setting standard in East Africa.",
        price: "KSh 850",
        rating: 4.9,
        stock: 250,
        image: "assets/images/products/hardware/photo_20_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_20_2026-03-09_04-54-32.jpg", "assets/images/products/hardware/photo_21_2026-03-09_04-54-32.jpg"],
        brand: "Bamburi",
        specs: { "Weight": "50kg", "Grade": "32.5N", "Curing Time": "28 Days" }
    },
    {
        id: "HW-BLD-002",
        category: "Building Materials",
        name: "Simba Cement",
        description: "Reliable and durable Portland cement for masonry and concrete works.",
        price: "KSh 830",
        rating: 4.7,
        stock: 180,
        image: "assets/images/products/hardware/photo_22_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_22_2026-03-09_04-54-32.jpg"],
        brand: "National Cement",
        specs: { "Weight": "50kg", "Grade": "32.5R" }
    },
    {
        id: "HW-BLD-003",
        category: "Building Materials",
        name: "Savannah Cement",
        description: "Premium quality cement offering high early strength for fast-paced construction.",
        price: "KSh 860",
        rating: 4.8,
        stock: 120,
        image: "assets/images/products/hardware/photo_23_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_23_2026-03-09_04-54-32.jpg"],
        brand: "Savannah",
        specs: { "Weight": "50kg", "Benefits": "High early strength" }
    },
    {
        id: "HW-BLD-004",
        category: "Building Materials",
        name: "Twiga Cement",
        description: "Versatile Portland composite cement perfect for block making and plastering.",
        price: "KSh 840",
        rating: 4.6,
        stock: 95,
        image: "assets/images/products/hardware/photo_24_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_24_2026-03-09_04-54-32.jpg"],
        brand: "Twiga",
        specs: { "Weight": "50kg", "Type": "Composite" }
    },

    // Plumbing & Sanitary
    {
        id: "HW-PLM-001",
        category: "Plumbing & Sanitary",
        name: "PPR Pipes & Fittings Bundle",
        description: "High-grade heat-fused PPR pipes and elbows for modern hot and cold water installations.",
        price: "KSh 2,500",
        rating: 4.7,
        stock: 80,
        image: "assets/images/products/hardware/photo_15_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_15_2026-03-09_04-54-32.jpg", "assets/images/products/hardware/photo_16_2026-03-09_04-54-32.jpg"],
        brand: "Generic Specs",
        specs: { "Material": "PPR", "Type": "PN20", "Use": "Hot/Cold Water" }
    },
    {
        id: "HW-PLM-002",
        category: "Plumbing & Sanitary",
        name: "PVC Drainage Pipes",
        description: "Durable PVC pipes for heavy-duty sewage and drainage systems in residential complexes.",
        price: "KSh 1,200",
        rating: 4.5,
        stock: 100,
        image: "assets/images/products/hardware/photo_17_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_17_2026-03-09_04-54-32.jpg"],
        brand: "Generic",
        specs: { "Diameter": "4 Inch / 110mm", "Length": "6 Meters", "Use": "Drainage" }
    },
    {
        id: "HW-PLM-003",
        category: "Plumbing & Sanitary",
        name: "Stainless Steel Kitchen Sink",
        description: "Heavy-duty double bowl stainless steel sink with drainboard. Rust-resistant.",
        price: "KSh 8,500",
        rating: 4.8,
        stock: 15,
        image: "assets/images/products/hardware/photo_18_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_18_2026-03-09_04-54-32.jpg"],
        brand: "EuroBath",
        specs: { "Material": "Stainless Steel 304", "Bowls": "Double", "Mount": "Top-mount" }
    },
    {
        id: "HW-PLM-004",
        category: "Plumbing & Sanitary",
        name: "Premium Bathroom Faucet",
        description: "Chrome-plated brass basin mixer tap with smooth ceramic cartridge technology.",
        price: "KSh 3,200",
        rating: 4.9,
        stock: 28,
        image: "assets/images/products/hardware/photo_19_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_19_2026-03-09_04-54-32.jpg"],
        brand: "Grohe Style",
        specs: { "Material": "Brass", "Finish": "Chrome", "Type": "Mixer" }
    },

    // Tools & Hardware
    {
        id: "HW-TLS-001",
        category: "Tools & Hardware",
        name: "Professional Masonry Trowel Set",
        description: "Forged steel brick-laying trowels with ergonomic grip handles for professional masons.",
        price: "KSh 1,800",
        rating: 4.6,
        stock: 35,
        image: "assets/images/products/hardware/photo_25_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_25_2026-03-09_04-54-32.jpg"],
        brand: "Stanley",
        specs: { "Material": "Carbon Steel", "Handle": "Rubberized", "Sizes": "Assorted" }
    },
    {
        id: "HW-TLS-002",
        category: "Tools & Hardware",
        name: "Heavy Duty Paint Rollers",
        description: "Solvent-resistant micro-fiber paint rollers. Ideal for applying both emulsion and gloss paints smoothly.",
        price: "KSh 450",
        rating: 4.5,
        stock: 120,
        image: "assets/images/products/hardware/photo_26_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_26_2026-03-09_04-54-32.jpg"],
        brand: "Harris",
        specs: { "Size": "9 Inch", "Material": "Microfiber" }
    },
    {
        id: "HW-TLS-003",
        category: "Tools & Hardware",
        name: "Makita Angle Grinder 115mm",
        description: "Compact 720W angle grinder for cutting metal and masonry. Includes safety guard and side handle.",
        price: "KSh 7,500",
        rating: 4.9,
        stock: 12,
        image: "assets/images/products/hardware/photo_27_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_27_2026-03-09_04-54-32.jpg"],
        brand: "Makita",
        specs: { "Power": "720W", "Disc Size": "115mm", "RPM": "11,000" }
    },
    {
        id: "HW-TLS-004",
        category: "Tools & Hardware",
        name: "Bosch Impact Drill Set",
        description: "Professional power drill with hammer action. Comes with assorted wood and concrete drill bits.",
        price: "KSh 12,500",
        rating: 4.8,
        stock: 8,
        image: "assets/images/products/hardware/photo_28_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_28_2026-03-09_04-54-32.jpg"],
        brand: "Bosch",
        specs: { "Power": "600W", "Type": "Impact Drill", "Accessories": "15pcs Bits" }
    },
    {
        id: "HW-TLS-005",
        category: "Tools & Hardware",
        name: "Tri-Circle Padlocks Assorted",
        description: "Classic brass heavy-duty padlocks for gates, doors, and storage containers. Anti-rust.",
        price: "KSh 1,200",
        rating: 4.7,
        stock: 65,
        image: "assets/images/products/hardware/photo_29_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_29_2026-03-09_04-54-32.jpg"],
        brand: "Tri-Circle",
        specs: { "Material": "Brass", "Keys": "3 per lock", "Sizes": "38mm, 50mm, 63mm" }
    },

    // Tiles & Flooring
    {
        id: "HW-TIL-001",
        category: "Tiles & Flooring",
        name: "Ceramic Floor Tiles 40x40",
        description: "Non-slip matte ceramic floor tiles ideal for kitchens, bathrooms, and corridors.",
        price: "KSh 950",
        rating: 4.6,
        stock: 200,
        image: "assets/images/products/hardware/photo_30_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_30_2026-03-09_04-54-32.jpg"],
        brand: "Saj Ceramics",
        specs: { "Size": "40x40 cm", "Finish": "Matte", "Box Contains": "1.6 sqm" }
    },
    {
        id: "HW-TIL-002",
        category: "Tiles & Flooring",
        name: "Porcelain Wood-Look Floor Tiles",
        description: "Premium porcelain floor tiles with a realistic timber grain texture. Highly durable and scratch-resistant.",
        price: "KSh 1,450",
        rating: 4.9,
        stock: 150,
        image: "assets/images/products/hardware/photo_31_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_31_2026-03-09_04-54-32.jpg"],
        brand: "Twyford",
        specs: { "Size": "15x60 cm", "Finish": "Wood Texture", "Box Contains": "1.0 sqm" }
    },
    {
        id: "HW-TIL-003",
        category: "Tiles & Flooring",
        name: "White Gloss Wall Tiles 30x60",
        description: "Bright white glossy wall tiles to give bathrooms and kitchens a clean, modern look.",
        price: "KSh 1,100",
        rating: 4.7,
        stock: 300,
        image: "assets/images/products/hardware/photo_32_2026-03-09_04-54-32.jpg",
        images: ["assets/images/products/hardware/photo_32_2026-03-09_04-54-32.jpg"],
        brand: "Twyford",
        specs: { "Size": "30x60 cm", "Finish": "Gloss", "Box Contains": "1.44 sqm" }
    }
];

window.RenovyteProducts = HardwareProducts;