const HardwareProducts = [
    {
        id: "HW-PAI-001",
        category: "Paints & Finishes",
        name: "Basco Value Permaflat Plus Emulsion 20L",
        description: "Premium quality basco value permaflat plus emulsion 20l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/BASCO VALUE PERMAFLAT PLUS EMULSION 20L.jpg",
        images: ["assets/images/products/hardware/BASCO VALUE PERMAFLAT PLUS EMULSION 20L.jpg"],
        brand: "Basco",
        specs: { "Brand": "Basco" }
    },
    {
        id: "HW-PAI-002",
        category: "Paints & Finishes",
        name: "Basco Value Permaflat Plus Emulsion",
        description: "Premium quality basco value permaflat plus emulsion for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/BASCO VALUE PERMAFLAT PLUS EMULSION.jpg",
        images: ["assets/images/products/hardware/BASCO VALUE PERMAFLAT PLUS EMULSION.jpg"],
        brand: "Basco",
        specs: { "Brand": "Basco" }
    },
    {
        id: "HW-PAI-003",
        category: "Paints & Finishes",
        name: "Caparol Capaplus Hiugh Sheen",
        description: "Premium quality caparol capaplus hiugh sheen for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CAPAROL CAPAPLUS HIUGH SHEEN.jpg",
        images: ["assets/images/products/hardware/CAPAROL CAPAPLUS HIUGH SHEEN.jpg"],
        brand: "Caparol",
        specs: { "Brand": "Caparol" }
    },
    {
        id: "HW-PAI-004",
        category: "Paints & Finishes",
        name: "Caparol",
        description: "Premium quality caparol for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CAPAROL.jpg",
        images: ["assets/images/products/hardware/CAPAROL.jpg"],
        brand: "Caparol",
        specs: { "Brand": "Caparol" }
    },
    {
        id: "HW-PAI-005",
        category: "Paints & Finishes",
        name: "Crown Aqua Glow 4L",
        description: "Premium quality crown aqua glow 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN AQUA GLOW 4L.jpg",
        images: ["assets/images/products/hardware/CROWN AQUA GLOW 4L.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-006",
        category: "Paints & Finishes",
        name: "Crown Covermatt 20L",
        description: "Premium quality crown covermatt 20l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN COVERMATT 20L.jpg",
        images: ["assets/images/products/hardware/CROWN COVERMATT 20L.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-007",
        category: "Paints & Finishes",
        name: "Crown Covermatt 4L",
        description: "Premium quality crown covermatt 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN COVERMATT 4L.jpg",
        images: ["assets/images/products/hardware/CROWN COVERMATT 4L.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-008",
        category: "Paints & Finishes",
        name: "Crown Emulsion Undercoat",
        description: "Premium quality crown emulsion undercoat for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN EMULSION UNDERCOAT.jpg",
        images: ["assets/images/products/hardware/CROWN EMULSION UNDERCOAT.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-009",
        category: "Paints & Finishes",
        name: "Crown Permaplast 20L",
        description: "Premium quality crown permaplast 20l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN PERMAPLAST 20L.jpg",
        images: ["assets/images/products/hardware/CROWN PERMAPLAST 20L.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-010",
        category: "Paints & Finishes",
        name: "Crown Permaplast 4L",
        description: "Premium quality crown permaplast 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN PERMAPLAST 4L.jpg",
        images: ["assets/images/products/hardware/CROWN PERMAPLAST 4L.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-011",
        category: "Paints & Finishes",
        name: "Crown Ruff N Tuff 30KG",
        description: "Premium quality crown ruff n tuff 30kg for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN RUFF n TUFF 30KG.jpg",
        images: ["assets/images/products/hardware/CROWN RUFF n TUFF 30KG.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-012",
        category: "Paints & Finishes",
        name: "Crown Silk Vinyl Emulsion 20L",
        description: "Premium quality crown silk vinyl emulsion 20l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN SILK VINYL EMULSION 20L.jpg",
        images: ["assets/images/products/hardware/CROWN SILK VINYL EMULSION 20L.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-013",
        category: "Paints & Finishes",
        name: "Crown Silk Vinyl Emulsion 4L",
        description: "Premium quality crown silk vinyl emulsion 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN SILK VINYL EMULSION 4L.jpg",
        images: ["assets/images/products/hardware/CROWN SILK VINYL EMULSION 4L.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-014",
        category: "Paints & Finishes",
        name: "Crown Stronghold",
        description: "Premium quality crown stronghold for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN STRONGHOLD.jpg",
        images: ["assets/images/products/hardware/CROWN STRONGHOLD.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-015",
        category: "Paints & Finishes",
        name: "Crown Supergloss 4L",
        description: "Premium quality crown supergloss 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN SUPERGLOSS 4L.jpg",
        images: ["assets/images/products/hardware/CROWN SUPERGLOSS 4L.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-016",
        category: "Paints & Finishes",
        name: "Crown Transeal 4L",
        description: "Premium quality crown transeal 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN TRANSEAL 4L.jpg",
        images: ["assets/images/products/hardware/CROWN TRANSEAL 4L.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-017",
        category: "Paints & Finishes",
        name: "Crown Ultraguard Silicone 20L",
        description: "Premium quality crown ultraguard silicone 20l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN ULTRAGUARD SILICONE 20L.jpg",
        images: ["assets/images/products/hardware/CROWN ULTRAGUARD SILICONE 20L.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-018",
        category: "Paints & Finishes",
        name: "Crown Ultraguard Silicone 4L",
        description: "Premium quality crown ultraguard silicone 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN ULTRAGUARD SILICONE 4L.jpg",
        images: ["assets/images/products/hardware/CROWN ULTRAGUARD SILICONE 4L.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-019",
        category: "Paints & Finishes",
        name: "Crown Universal Undercoat",
        description: "Premium quality crown universal undercoat for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN UNIVERSAL UNDERCOAT.jpg",
        images: ["assets/images/products/hardware/CROWN UNIVERSAL UNDERCOAT.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-020",
        category: "Paints & Finishes",
        name: "Crown Vesta Gloss 4L",
        description: "Premium quality crown vesta gloss 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN VESTA GLOSS 4L.jpg",
        images: ["assets/images/products/hardware/CROWN VESTA GLOSS 4L.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-021",
        category: "Paints & Finishes",
        name: "Crown Vestya Metal Primer",
        description: "Premium quality crown vestya metal primer for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN VESTYA METAL PRIMER.jpg",
        images: ["assets/images/products/hardware/CROWN VESTYA METAL PRIMER.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-022",
        category: "Paints & Finishes",
        name: "Crown Vinyl Matt Emulsion Luxury 20L",
        description: "Premium quality crown vinyl matt emulsion luxury 20l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN VINYL MATT EMULSION LUXURY 20L.jpg",
        images: ["assets/images/products/hardware/CROWN VINYL MATT EMULSION LUXURY 20L.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-023",
        category: "Paints & Finishes",
        name: "Crown Vinyl Matt Emulsion Luxury 4L",
        description: "Premium quality crown vinyl matt emulsion luxury 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN VINYL MATT EMULSION LUXURY 4L.jpg",
        images: ["assets/images/products/hardware/CROWN VINYL MATT EMULSION LUXURY 4L.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-024",
        category: "Paints & Finishes",
        name: "Crown Walplast Skim Coat",
        description: "Premium quality crown walplast skim coat for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN WALPLAST SKIM COAT.jpg",
        images: ["assets/images/products/hardware/CROWN WALPLAST SKIM COAT.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-025",
        category: "Paints & Finishes",
        name: "Crown Wood Master 4L",
        description: "Premium quality crown wood master 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN WOOD MASTER 4L.jpg",
        images: ["assets/images/products/hardware/CROWN WOOD MASTER 4L.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-026",
        category: "Paints & Finishes",
        name: "Crown Wood Master Multipurpose Varnish 4L",
        description: "Premium quality crown wood master multipurpose varnish 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN WOOD MASTER MULTIPURPOSE VARNISH 4L.jpg",
        images: ["assets/images/products/hardware/CROWN WOOD MASTER MULTIPURPOSE VARNISH 4L.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-027",
        category: "Paints & Finishes",
        name: "Crown Wood Master Polyurethane Clear Vanish 4L",
        description: "Premium quality crown wood master polyurethane clear vanish 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/CROWN WOOD MASTER POLYURETHANE CLEAR VANISH 4L.jpg",
        images: ["assets/images/products/hardware/CROWN WOOD MASTER POLYURETHANE CLEAR VANISH 4L.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-028",
        category: "Paints & Finishes",
        name: "Dr Fix It Sure Seal",
        description: "Premium quality dr fix it sure seal for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/DR FIX IT SURE SEAL.jpg",
        images: ["assets/images/products/hardware/DR FIX IT SURE SEAL.jpg"],
        brand: "Generic",
        specs: { "Brand": "Generic" }
    },
    {
        id: "HW-PAI-029",
        category: "Paints & Finishes",
        name: "Dura Coat Weathercoat 20L",
        description: "Premium quality dura coat weathercoat 20l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/DURA COAT WEATHERCOAT 20L.jpg",
        images: ["assets/images/products/hardware/DURA COAT WEATHERCOAT 20L.jpg"],
        brand: "DuraCoat",
        specs: { "Brand": "DuraCoat" }
    },
    {
        id: "HW-PAI-030",
        category: "Paints & Finishes",
        name: "Duracoat Acrylic Sealer 4L",
        description: "Premium quality duracoat acrylic sealer 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/DURACOAT ACRYLIC SEALER 4L.jpg",
        images: ["assets/images/products/hardware/DURACOAT ACRYLIC SEALER 4L.jpg"],
        brand: "DuraCoat",
        specs: { "Brand": "DuraCoat" }
    },
    {
        id: "HW-PAI-031",
        category: "Paints & Finishes",
        name: "Duracoat Floor Paint 4L",
        description: "Premium quality duracoat floor paint 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/DURACOAT FLOOR PAINT 4L.jpg",
        images: ["assets/images/products/hardware/DURACOAT FLOOR PAINT 4L.jpg"],
        brand: "DuraCoat",
        specs: { "Brand": "DuraCoat" }
    },
    {
        id: "HW-PAI-032",
        category: "Paints & Finishes",
        name: "Duracoat Pu Foam",
        description: "Premium quality duracoat pu foam for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/DURACOAT PU FOAM .jpg",
        images: ["assets/images/products/hardware/DURACOAT PU FOAM .jpg"],
        brand: "DuraCoat",
        specs: { "Brand": "DuraCoat" }
    },
    {
        id: "HW-PAI-033",
        category: "Paints & Finishes",
        name: "Duracoat Real Roc 30KG",
        description: "Premium quality duracoat real roc 30kg for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/DURACOAT REAL ROC 30KG.jpg",
        images: ["assets/images/products/hardware/DURACOAT REAL ROC 30KG.jpg"],
        brand: "DuraCoat",
        specs: { "Brand": "DuraCoat" }
    },
    {
        id: "HW-PAI-034",
        category: "Paints & Finishes",
        name: "Duracoat Roof Paint 4L",
        description: "Premium quality duracoat roof paint 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/DURACOAT ROOF PAINT 4L.jpg",
        images: ["assets/images/products/hardware/DURACOAT ROOF PAINT 4L.jpg"],
        brand: "DuraCoat",
        specs: { "Brand": "DuraCoat" }
    },
    {
        id: "HW-PAI-035",
        category: "Paints & Finishes",
        name: "Duracoat Rooftec Roof Paint 4L",
        description: "Premium quality duracoat rooftec roof paint 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/DURACOAT ROOFTEC ROOF PAINT 4L.jpg",
        images: ["assets/images/products/hardware/DURACOAT ROOFTEC ROOF PAINT 4L.jpg"],
        brand: "DuraCoat",
        specs: { "Brand": "DuraCoat" }
    },
    {
        id: "HW-PAI-036",
        category: "Paints & Finishes",
        name: "Duracoat Silicone Exterior Emulsion 20L",
        description: "Premium quality duracoat silicone exterior emulsion 20l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/DURACOAT SILICONE EXTERIOR EMULSION 20L.jpg",
        images: ["assets/images/products/hardware/DURACOAT SILICONE EXTERIOR EMULSION 20L.jpg"],
        brand: "DuraCoat",
        specs: { "Brand": "DuraCoat" }
    },
    {
        id: "HW-PAI-037",
        category: "Paints & Finishes",
        name: "Duracoat Silicone Exterior Emulsion 4L",
        description: "Premium quality duracoat silicone exterior emulsion 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/DURACOAT SILICONE EXTERIOR EMULSION 4L.jpg",
        images: ["assets/images/products/hardware/DURACOAT SILICONE EXTERIOR EMULSION 4L.jpg"],
        brand: "DuraCoat",
        specs: { "Brand": "DuraCoat" }
    },
    {
        id: "HW-PAI-038",
        category: "Paints & Finishes",
        name: "Duracoat Skim Coat",
        description: "Premium quality duracoat skim coat for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/DURACOAT SKIM COAT.jpg",
        images: ["assets/images/products/hardware/DURACOAT SKIM COAT.jpg"],
        brand: "DuraCoat",
        specs: { "Brand": "DuraCoat" }
    },
    {
        id: "HW-PAI-039",
        category: "Paints & Finishes",
        name: "Duracoat Superfast",
        description: "Premium quality duracoat superfast for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/DURACOAT SUPERFAST .jpg",
        images: ["assets/images/products/hardware/DURACOAT SUPERFAST .jpg"],
        brand: "DuraCoat",
        specs: { "Brand": "DuraCoat" }
    },
    {
        id: "HW-PAI-040",
        category: "Paints & Finishes",
        name: "Duracoat Superfast",
        description: "Premium quality duracoat superfast for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/DURACOAT SUPERFAST.jpg",
        images: ["assets/images/products/hardware/DURACOAT SUPERFAST.jpg"],
        brand: "DuraCoat",
        specs: { "Brand": "DuraCoat" }
    },
    {
        id: "HW-PAI-041",
        category: "Paints & Finishes",
        name: "Duracoat Supergloss 4L",
        description: "Premium quality duracoat supergloss 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/DURACOAT SUPERGLOSS 4L.jpg",
        images: ["assets/images/products/hardware/DURACOAT SUPERGLOSS 4L.jpg"],
        brand: "DuraCoat",
        specs: { "Brand": "DuraCoat" }
    },
    {
        id: "HW-PAI-042",
        category: "Paints & Finishes",
        name: "Duracoat Vinyl Silk 4L",
        description: "Premium quality duracoat vinyl silk 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/DURACOAT VINYL SILK 4L.jpg",
        images: ["assets/images/products/hardware/DURACOAT VINYL SILK 4L.jpg"],
        brand: "DuraCoat",
        specs: { "Brand": "DuraCoat" }
    },
    {
        id: "HW-PAI-043",
        category: "Paints & Finishes",
        name: "Duracoat Woodtech 4L",
        description: "Premium quality duracoat woodtech 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/DURACOAT WOODTECH 4L.jpg",
        images: ["assets/images/products/hardware/DURACOAT WOODTECH 4L.jpg"],
        brand: "DuraCoat",
        specs: { "Brand": "DuraCoat" }
    },
    {
        id: "HW-PAI-044",
        category: "Paints & Finishes",
        name: "Duracoat Duraplast 4L",
        description: "Premium quality duracoat duraplast 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/Duracoat Duraplast 4L.jpg",
        images: ["assets/images/products/hardware/Duracoat Duraplast 4L.jpg"],
        brand: "DuraCoat",
        specs: { "Brand": "DuraCoat" }
    },
    {
        id: "HW-BUI-045",
        category: "Building Materials",
        name: "Gyproc",
        description: "Premium quality gyproc for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/GYPROC.jpg",
        images: ["assets/images/products/hardware/GYPROC.jpg"],
        brand: "Generic",
        specs: { "Brand": "Generic" }
    },
    {
        id: "HW-PAI-046",
        category: "Paints & Finishes",
        name: "Robbialac Vinyl Silk Emulsion",
        description: "Premium quality robbialac vinyl silk emulsion for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/ROBBIALAC VINYL SILK EMULSION.jpg",
        images: ["assets/images/products/hardware/ROBBIALAC VINYL SILK EMULSION.jpg"],
        brand: "Berger",
        specs: { "Brand": "Berger" }
    },
    {
        id: "HW-TOO-047",
        category: "Tools & Hardware",
        name: "Roller Cover",
        description: "Premium quality roller cover for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/ROLLER COVER.jpg",
        images: ["assets/images/products/hardware/ROLLER COVER.jpg"],
        brand: "Generic",
        specs: { "Brand": "Generic" }
    },
    {
        id: "HW-PAI-048",
        category: "Paints & Finishes",
        name: "Special Effects",
        description: "Premium quality special effects for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/SPECIAL EFFECTS.jpg",
        images: ["assets/images/products/hardware/SPECIAL EFFECTS.jpg"],
        brand: "Generic",
        specs: { "Brand": "Generic" }
    },
    {
        id: "HW-PAI-049",
        category: "Paints & Finishes",
        name: "Texturz 30KGs",
        description: "Premium quality texturz 30kgs for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/TEXTURZ 30KGS.jpg",
        images: ["assets/images/products/hardware/TEXTURZ 30KGS.jpg"],
        brand: "Generic",
        specs: { "Brand": "Generic" }
    },
    {
        id: "HW-PAI-050",
        category: "Paints & Finishes",
        name: "Ultima Aqua Gloss Enamel 4L",
        description: "Premium quality ultima aqua gloss enamel 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/ULTIMA AQUA GLOSS ENAMEL 4L.jpg",
        images: ["assets/images/products/hardware/ULTIMA AQUA GLOSS ENAMEL 4L.jpg"],
        brand: "Generic",
        specs: { "Brand": "Generic" }
    },
    {
        id: "HW-PAI-051",
        category: "Paints & Finishes",
        name: "Woodtech Nc Sanding Sealer 4L",
        description: "Premium quality woodtech nc sanding sealer 4l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/WOODTECH NC SANDING SEALER 4L.jpg",
        images: ["assets/images/products/hardware/WOODTECH NC SANDING SEALER 4L.jpg"],
        brand: "Generic",
        specs: { "Brand": "Generic" }
    },
    {
        id: "HW-PAI-052",
        category: "Paints & Finishes",
        name: "Woodtech Timberex 5L",
        description: "Premium quality woodtech timberex 5l for professional and DIY use.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 50,
        image: "assets/images/products/hardware/WOODTECH TIMBEREX 5L.jpg",
        images: ["assets/images/products/hardware/WOODTECH TIMBEREX 5L.jpg"],
        brand: "Generic",
        specs: { "Brand": "Generic" }
    },
    {
        id: "HW-BUI-053",
        category: "Building Materials",
        name: "Crownplast Waterproof Skimcoat",
        description: "High-performance waterproof skimcoat by Crown, ideal for exterior and interior building surfaces.",
        price: "Ask for Price",
        rating: 4.9,
        stock: 50,
        image: "assets/images/products/hardware/CROWNPLAST WATERPROOF SKIMCOAT.jpg",
        images: ["assets/images/products/hardware/CROWNPLAST WATERPROOF SKIMCOAT.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-054",
        category: "Paints & Finishes",
        name: "Crown Rain Protek",
        description: "Advanced weather protection paint by Crown, designed to withstand heavy rain and moisture.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 40,
        image: "assets/images/products/hardware/CROWN RAIN PROTEK.jpg",
        images: ["assets/images/products/hardware/CROWN RAIN PROTEK.jpg"],
        brand: "Crown Paints",
        specs: { "Brand": "Crown Paints" }
    },
    {
        id: "HW-PAI-055",
        category: "Building Materials",
        name: "Dr Fix It Pidiproof",
        description: "Integral liquid waterproofing compound for cement mortar and concrete.",
        price: "Ask for Price",
        rating: 4.7,
        stock: 60,
        image: "assets/images/products/hardware/DR FIX IT PIDIPROOF.jpg",
        images: ["assets/images/products/hardware/DR FIX IT PIDIPROOF.jpg"],
        brand: "Dr Fix It",
        specs: { "Brand": "Dr Fix It" }
    },
    {
        id: "HW-PAI-056",
        category: "Building Materials",
        name: "Dr Fix It Super Latex",
        description: "SBR based modifier for repair and waterproofing. Multi-purpose latex for cementitious compositions.",
        price: "Ask for Price",
        rating: 4.8,
        stock: 45,
        image: "assets/images/products/hardware/DR FIX IT SUPER LATEX.jpg",
        images: ["assets/images/products/hardware/DR FIX IT SUPER LATEX.jpg"],
        brand: "Dr Fix It",
        specs: { "Brand": "Dr Fix It" }
    },
    {
        id: "HW-PAI-057",
        category: "Paints & Finishes",
        name: "DuraCoat Aqua Tech Rainshield",
        description: "DuraCoat's premium rain protection system for long-lasting exterior water resistance.",
        price: "Ask for Price",
        rating: 4.9,
        stock: 35,
        image: "assets/images/products/hardware/DURACOAT AQUA TECH RAINSHIELD.jpg",
        images: ["assets/images/products/hardware/DURACOAT AQUA TECH RAINSHIELD.jpg"],
        brand: "DuraCoat",
        specs: { "Brand": "DuraCoat" }
    },
];

window.RenovyteProducts = HardwareProducts;
